import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Separator } from "@radix-ui/react-separator";
import Link from "next/link";
import { cn } from "@/lib/utils";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const navItems = [
  { href: "/", label: "Dashboard" },
  { href: "/model", label: "Model" },
  { href: "/stores", label: "Stores" },
  { href: "/jobs", label: "Jobs" },
  { href: "/search", label: "Search" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`min-h-screen flex bg-gray-50 text-gray-900 ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Sidebar */}
        <aside className="w-60 bg-white border-r shadow-sm flex flex-col">
          <div className="px-4 py-6">
            <h1 className="text-xl font-bold">🔎 TinyFind</h1>
            <p className="text-xs text-muted-foreground">local embed search</p>
          </div>
          <Separator />
          <nav className="flex-1 px-3 py-4 space-y-1">
            {navItems.map((item) => (
              <Link
                key={item.href}
                href={item.href}
                className={cn(
                  "block rounded-md px-3 py-2 text-sm font-medium hover:bg-gray-100"
                )}
              >
                {item.label}
              </Link>
            ))}
          </nav>
          <div className="px-4 py-4 text-xs text-muted-foreground border-t">
            Running locally
          </div>
        </aside>

        {/* Main content */}
        <main className="flex-1 overflow-y-auto p-6">{children}</main>
      </body>
    </html>
  );
}
