version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - ALLOWED_ORIGINS=http://localhost:3000
    volumes:
      - ./backend/stores:/app/stores
      - huggingface-cache:/root/.cache/huggingface
    ports:
      - "8000:8000"
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
      args:
        NEXT_PUBLIC_API_BASE: http://backend:8000
    environment:
      - NEXT_PUBLIC_API_BASE=http://backend:8000
    depends_on:
      - backend
    ports:
      - "3000:3000"
volumes:
  huggingface-cache:
